/*
 * AKS VHD Security Advisories — static front-end.
 *
 * Zero build step, zero dependencies. It reads the JSON feed produced by
 * `aks-cve feed` (aksadvisory.feed): a small `index.json` (one compact entry
 * per CVE, plus `releases`/`severities`/`statuses` facets) and, on demand, the
 * per-CVE `advisories/<CVE>.json` files.
 *
 * Data location: resolved once at startup. On GitHub Pages the workflow places
 * the feed under `./data/`; for local preview (`python -m http.server` from the
 * repo root, open `/site/`) it transparently falls back to `../feed-out`. A
 * `?data=<base>` query override wins over both.
 */
"use strict";

/* ---------- glossary (single source of truth for tooltips + help page) ---------- */

// Per-status explanation. Reused by badge tooltips and the help page so the two
// never drift.
const STATUS_HELP = {
  fixed: "A scanned AKS VHD build ships a package version at or above the distro's fixed version. The 'first fixed build' field names the earliest build that carries the fix.",
  fix_available_upstream: "The distro (Azure Linux / Ubuntu) has published a fixed package, but none of the scanned VHD builds ship it yet. The fix exists upstream and is expected in a future node image.",
  affected: "Vulnerable, with no upstream fix available yet. (Not enumerable from OVAL alone, so rarely emitted by this feed — see the help page.)",
  not_affected: "Excluded by a vendor verdict — an Azure Linux CSAF/VEX justification or an Ubuntu CVE Tracker 'not-affected' (e.g. the vulnerable code path is not present/reachable). The justification is shown on the advisory.",
  under_investigation: "Triage is not complete — either no distro OVAL/VEX verdict exists yet, or the Ubuntu CVE Tracker marks the package 'needs-triage'.",
  will_not_fix: "The vendor will not ship a fix (Ubuntu CVE Tracker 'ignored' — e.g. the release is past standard support, or the fix is deemed too intrusive). The reason is shown on the advisory.",
};

const STATUS_LABELS = {
  fixed: "Fixed",
  fix_available_upstream: "Fix available upstream",
  affected: "Affected",
  not_affected: "Not affected",
  under_investigation: "Under investigation",
  will_not_fix: "Will not fix",
};

// Field/column explanations. Keyed by a short id used across the list and the
// detail view.
const FIELD_HELP = {
  cve: "The CVE identifier. Click it to open the full advisory with per-OS/SKU package status and evidence links.",
  severity: "Severity as reported by the distro advisory feed (OVAL): Critical, High, Medium, or Low. Sorted Critical → Low.",
  status: "The single most-actionable status across all OS/SKU lineages for this CVE (the 'headline' status). Open the advisory to see each lineage individually.",
  release: "The AKS VHD lineage(s) — OS family + generation/SKU, e.g. 'AzureLinux-V3/gen2' — where this CVE was assessed. Use the OS/SKU filter to narrow the list.",
  updated: "When this advisory record was last regenerated by the feed builder (UTC date).",
  search: "Filter the list live by CVE id substring, e.g. type '2026-4' to match CVE-2026-4xxx.",
  package: "The base-OS package (as named in the distro OVAL feed) affected by this CVE, e.g. 'expat' or 'openssl'.",
  fixed_version: "The distro package version that resolves the CVE, and which a shipping VHD build was confirmed to carry.",
  upstream_fixed_version: "The distro package version that resolves the CVE upstream. No scanned VHD build ships it yet.",
  first_fixed_build: "The earliest scanned AKS VHD build whose installed package reaches the fixed version. A 'security-patch:<version>' value means the fix landed via a security-patch delta rather than a full build.",
  latest_build: "The newest scanned AKS VHD build (still on a pre-fix package version) — the baseline the 'fix available upstream' verdict was measured against.",
  advisory_id: "The distro advisory identifier the fixed version came from (e.g. an Azure Linux OVAL advisory id).",
  evidence: "Verifiable source links backing the verdict: the AgentBaker release-notes file listing the exact installed versions, and the distro OVAL/advisory feed.",
  additive: "Binaries laid on top of the base image (kubelet, CNI, containerd/runc) and cached container images. These are tracked by their own upstreams, NOT the distro advisory feeds, so this feed does not assert a fix status for them (coverage: not_assessed).",
  references: "External references for this CVE — NVD, the distro security tracker, and the advisory feed source.",
};

const SEVERITY_RANK = { Critical: 0, High: 1, Medium: 2, Low: 3 };

const state = {
  dataBase: "data",
  index: null,      // parsed index.json
  entries: [],      // index.advisories
  filters: { q: "", release: "", status: "", severity: "" },
  detailCache: new Map(),
};

const $app = () => document.getElementById("app");

/* ---------- data loading ---------- */

async function resolveDataBase() {
  const override = new URLSearchParams(location.search).get("data");
  const candidates = override
    ? [override.replace(/\/+$/, "")]
    : ["data", "../feed-out"];
  for (const base of candidates) {
    try {
      const r = await fetch(base + "/index.json", { method: "HEAD" });
      if (r.ok) return base;
    } catch (_e) { /* try next */ }
  }
  return candidates[0];
}

async function loadIndex() {
  state.dataBase = await resolveDataBase();
  const r = await fetch(state.dataBase + "/index.json");
  if (!r.ok) throw new Error("index.json HTTP " + r.status);
  state.index = await r.json();
  state.entries = state.index.advisories || [];
}

async function loadAdvisory(id) {
  if (state.detailCache.has(id)) return state.detailCache.get(id);
  const r = await fetch(state.dataBase + "/advisories/" + encodeURIComponent(id) + ".json");
  if (!r.ok) throw new Error(id + " HTTP " + r.status);
  const adv = await r.json();
  state.detailCache.set(id, adv);
  return adv;
}

/* ---------- dom helpers ---------- */

function el(tag, attrs, children) {
  const n = document.createElement(tag);
  if (attrs) {
    for (const [k, v] of Object.entries(attrs)) {
      if (v == null) continue;
      if (k === "class") n.className = v;
      else if (k === "html") n.innerHTML = v;
      else if (k.startsWith("on") && typeof v === "function") n.addEventListener(k.slice(2), v);
      else n.setAttribute(k, v);
    }
  }
  for (const c of [].concat(children || [])) {
    if (c == null) continue;
    n.appendChild(typeof c === "string" ? document.createTextNode(c) : c);
  }
  return n;
}

// An accessible info affordance: shows `text` on hover (CSS bubble via data-tip),
// on keyboard focus (tabindex), and to screen readers / native title.
function info(text) {
  return el("span", {
    class: "info", tabindex: "0", role: "note",
    "data-tip": text, "aria-label": text, title: text,
  }, "\u24D8"); // ⓘ
}

// A label followed by its info icon (for table headers / detail field labels).
function labelWithInfo(text, helpKey) {
  const help = FIELD_HELP[helpKey];
  return el("span", { class: "hlabel" }, [text, help ? info(help) : null]);
}

function statusBadge(status) {
  return el("span", {
    class: "badge st-" + status,
    title: (STATUS_LABELS[status] || status) + " — " + (STATUS_HELP[status] || ""),
  }, STATUS_LABELS[status] || status || "\u2014");
}

function severityCell(sev) {
  return el("span", {
    class: "sev sev-" + (sev || ""),
    title: sev ? "Severity: " + sev : null,
  }, sev || "\u2014");
}

function isExternal(url) { return /^https?:\/\//i.test(url || ""); }

/* ---------- list view ---------- */

// Newest CVE first. CVE ids look like `CVE-<year>-<seq>`; the sequence is NOT
// zero-padded, so a plain string sort mis-orders (e.g. "...-9" > "...-1234").
// Compare year then sequence numerically, both descending.
function compareCveDesc(a, b) {
  const pa = /^CVE-(\d+)-(\d+)$/i.exec(a.id);
  const pb = /^CVE-(\d+)-(\d+)$/i.exec(b.id);
  if (pa && pb) {
    const yd = Number(pb[1]) - Number(pa[1]);
    if (yd) return yd;
    const sd = Number(pb[2]) - Number(pa[2]);
    if (sd) return sd;
  }
  return b.id.localeCompare(a.id);
}

function applyFilters() {
  const { q, release, status, severity } = state.filters;
  const needle = q.trim().toLowerCase();
  return state.entries.filter((e) => {
    if (needle && !e.id.toLowerCase().includes(needle)) return false;
    if (release && !(e.releases || []).includes(release)) return false;
    if (status && e.headline_status !== status) return false;
    if (severity && e.severity !== severity) return false;
    return true;
  }).sort(compareCveDesc);
}

function renderControls() {
  const idx = state.index;
  const opt = (val, label, sel) =>
    el("option", { value: val, selected: sel === val ? "selected" : null }, label);

  const releaseSel = el("select", { id: "f-release", "aria-label": "Filter by OS / SKU" }, [
    opt("", "All OS / SKUs", state.filters.release),
    ...(idx.releases || []).map((r) => opt(r, r, state.filters.release)),
  ]);
  const statusSel = el("select", { id: "f-status", "aria-label": "Filter by status" }, [
    opt("", "All statuses", state.filters.status),
    ...(idx.statuses || Object.keys(STATUS_LABELS)).map((s) =>
      opt(s, STATUS_LABELS[s] || s, state.filters.status)),
  ]);
  const sevSel = el("select", { id: "f-sev", "aria-label": "Filter by severity" }, [
    opt("", "All severities", state.filters.severity),
    ...(idx.severities || []).slice().sort((a, b) =>
      (SEVERITY_RANK[a] ?? 9) - (SEVERITY_RANK[b] ?? 9)).map((s) =>
      opt(s, s, state.filters.severity)),
  ]);
  const search = el("input", {
    id: "f-q", type: "search", placeholder: "Search CVE id, e.g. CVE-2026-4",
    value: state.filters.q, autocomplete: "off", spellcheck: "false",
  });

  search.addEventListener("input", () => { state.filters.q = search.value; renderList(); });
  releaseSel.addEventListener("change", () => { state.filters.release = releaseSel.value; renderList(); });
  statusSel.addEventListener("change", () => { state.filters.status = statusSel.value; renderList(); });
  sevSel.addEventListener("change", () => { state.filters.severity = sevSel.value; renderList(); });

  return el("div", { class: "controls" }, [
    el("div", { class: "field" }, [
      el("label", { for: "f-q" }, [labelWithInfo("Search", "search")]), search]),
    el("div", { class: "field" }, [
      el("label", { for: "f-release" }, [labelWithInfo("OS / SKU", "release")]), releaseSel]),
    el("div", { class: "field" }, [
      el("label", { for: "f-status" }, [labelWithInfo("Status", "status")]), statusSel]),
    el("div", { class: "field" }, [
      el("label", { for: "f-sev" }, [labelWithInfo("Severity", "severity")]), sevSel]),
  ]);
}

function renderRows(rows) {
  if (!rows.length) return el("p", { class: "empty" }, "No advisories match your filters.");
  const body = el("tbody", null, rows.map((e) => {
    const releases = (e.releases || []).map((r) => el("span", { class: "chip" }, r));
    return el("tr", null, [
      el("td", { class: "cve" }, el("a", { href: "#/" + e.id }, e.id)),
      el("td", null, severityCell(e.severity)),
      el("td", null, statusBadge(e.headline_status)),
      el("td", null, releases.length ? releases : "\u2014"),
      el("td", { class: "mono muted" }, (e.updated || "").slice(0, 10) || "\u2014"),
    ]);
  }));
  return el("div", { class: "table-wrap" }, el("table", null, [
    el("thead", null, el("tr", null, [
      el("th", null, [labelWithInfo("CVE", "cve")]),
      el("th", null, [labelWithInfo("Severity", "severity")]),
      el("th", null, [labelWithInfo("Status", "status")]),
      el("th", null, [labelWithInfo("OS / SKU", "release")]),
      el("th", null, [labelWithInfo("Updated", "updated")]),
    ])),
    body,
  ]));
}

function renderList() {
  // Re-render only the results region when it already exists (keeps focus in
  // the search box); otherwise build the whole view.
  const rows = applyFilters();
  let container = document.getElementById("results");
  if (!container) {
    const meta = el("div", { class: "result-meta" }, [
      el("span", { id: "count" }, ""),
      el("button", { onclick: resetFilters }, "Reset filters"),
    ]);
    const view = el("div", null, [
      el("p", { class: "intro" }, [
        "Fix status of known CVEs in the base-OS packages of recent AKS node images. ",
        el("a", { href: "#/help" }, "How to read this →"),
      ]),
      renderControls(), meta, el("div", { id: "results" }),
    ]);
    $app().replaceChildren(view);
    container = document.getElementById("results");
  }
  container.replaceChildren(renderRows(rows));
  const count = document.getElementById("count");
  if (count) {
    count.textContent = rows.length + " of " + state.entries.length + " advisories";
  }
  setGeneratedFooter();
}

function resetFilters() {
  state.filters = { q: "", release: "", status: "", severity: "" };
  $app().replaceChildren();  // force full rebuild so control values reset
  renderList();
}

/* ---------- detail view ---------- */

function kv(dl, label, value, helpKey) {
  if (value == null || value === "") return;
  const help = helpKey && FIELD_HELP[helpKey];
  dl.appendChild(el("dt", null, [label, help ? info(help) : null]));
  dl.appendChild(el("dd", null, value));
}

function evidenceLinks(evidence) {
  if (!evidence) return null;
  const items = Object.entries(evidence).map(([k, v]) =>
    el("li", null, isExternal(v)
      ? [k.replace(/_/g, " ") + ": ", el("a", { href: v, target: "_blank", rel: "noopener" }, v)]
      : el("span", null, k.replace(/_/g, " ") + ": " + v)));
  return el("ul", { class: "ref-list" }, items);
}

function packageCard(row) {
  const dl = el("dl", { class: "kv" });
  kv(dl, "Status", statusBadge(row.status), "status");
  kv(dl, "Severity", row.severity, "severity");
  kv(dl, "Advisory id", row.advisory_id && el("span", { class: "mono" }, row.advisory_id), "advisory_id");
  kv(dl, "Fixed version", row.fixed_version && el("span", { class: "mono" }, row.fixed_version), "fixed_version");
  kv(dl, "Upstream fixed", row.upstream_fixed_version && el("span", { class: "mono" }, row.upstream_fixed_version), "upstream_fixed_version");
  kv(dl, "First fixed build", row.first_fixed_build && el("span", { class: "mono" }, row.first_fixed_build), "first_fixed_build");
  kv(dl, "Latest build", row.latest_build && el("span", { class: "mono" }, row.latest_build), "latest_build");
  kv(dl, "Justification", row.justification);
  kv(dl, "Statement", row.statement);
  const ev = evidenceLinks(row.evidence);
  const card = el("div", { class: "card" }, [
    el("h3", null, [row.release + " \u00b7 ", el("span", { class: "mono" }, row.package)]),
    dl,
  ]);
  if (ev) {
    card.appendChild(el("h3", null, ["Evidence", info(FIELD_HELP.evidence)]));
    card.appendChild(ev);
  }
  return card;
}

function renderDetail(adv) {
  // Gate href behind isExternal() (same as evidenceLinks) so only http(s)
  // URLs ever become clickable links; anything else renders as inert text.
  const refs = (adv.references || []).map((u) =>
    el("li", null, isExternal(u)
      ? el("a", { href: u, target: "_blank", rel: "noopener" }, u)
      : el("span", null, String(u))));

  const summary = el("div", { class: "card" }, [
    el("h3", null, "Summary"),
    (() => {
      const dl = el("dl", { class: "kv" });
      kv(dl, "Severity", severityCell(adv.severity), "severity");
      kv(dl, "Headline status", statusBadge(adv.headline_status), "status");
      kv(dl, "Updated", (adv.updated || "").slice(0, 10), "updated");
      kv(dl, "Schema", el("span", { class: "mono" }, adv.schema_version));
      return dl;
    })(),
    adv.description ? el("p", { class: "note" }, adv.description) : null,
  ]);

  const refsCard = refs.length
    ? el("div", { class: "card" }, [
        el("h3", null, ["References", info(FIELD_HELP.references)]),
        el("ul", { class: "ref-list" }, refs)])
    : null;

  const pkgCards = (adv.packages || []).map(packageCard);
  const pkgSection = pkgCards.length
    ? el("div", { class: "detail-grid" }, pkgCards)
    : el("p", { class: "empty" }, "No package rows.");

  const add = adv.additive || {};
  const additiveCard = el("div", { class: "card" }, [
    el("h3", null, ["Additive surface", info(FIELD_HELP.additive)]),
    el("p", { class: "note" }, "Coverage: " + (add.coverage || "n/a") + " \u2014 " + (add.note || "")),
    (add.items && add.items.length)
      ? el("ul", { class: "additive-items" }, add.items.map((i) =>
          el("li", null, typeof i === "string" ? i : JSON.stringify(i))))
      : null,
  ]);

  const view = el("div", null, [
    el("a", { class: "back", href: "#/" }, "\u2190 All advisories"),
    el("div", { class: "detail-head" }, [
      el("h2", null, adv.id),
      severityCell(adv.severity),
      statusBadge(adv.headline_status),
    ]),
    el("div", { class: "detail-grid" }, [summary, refsCard].filter(Boolean)),
    el("p", { class: "section-title" }, [
      "Package status by OS / SKU", info(FIELD_HELP.package)]),
    pkgSection,
    el("div", { style: "margin-top:1.25rem" }, additiveCard),
  ]);
  $app().replaceChildren(view);
}

/* ---------- help view ---------- */

function statusGlossary() {
  return el("div", { class: "glossary" }, Object.keys(STATUS_LABELS).map((s) =>
    el("div", { class: "gloss-row" }, [
      statusBadge(s),
      el("p", null, STATUS_HELP[s]),
    ])));
}

function renderHelp() {
  const view = el("div", { class: "help" }, [
    el("a", { class: "back", href: "#/" }, "\u2190 All advisories"),
    el("h2", null, "Help & glossary"),

    el("p", { class: "note" }, [
      "This site reports the fix status of known CVEs in the ",
      el("strong", null, "base-OS packages"),
      " (Azure Linux and Ubuntu) of recent AKS node images (VHDs). It is a ",
      "community project generated by the open-source ",
      el("a", { href: "https://github.com/chrischangcode/aks-security-advisory", target: "_blank", rel: "noopener" },
        "aks-security-advisory"),
      " tool — it is not an official Microsoft security feed.",
    ]),

    el("h3", null, "Status vocabulary"),
    el("p", { class: "note" }, "Each CVE gets a single headline status (the most actionable across all OS/SKU lineages). On an advisory page you can see each lineage's own status."),
    statusGlossary(),

    el("h3", null, "Columns & fields"),
    (() => {
      const dl = el("dl", { class: "kv help-kv" });
      const order = ["cve", "severity", "status", "release", "updated",
        "package", "fixed_version", "upstream_fixed_version",
        "first_fixed_build", "latest_build", "advisory_id", "evidence",
        "references", "additive"];
      for (const k of order) {
        dl.appendChild(el("dt", null, k.replace(/_/g, " ")));
        dl.appendChild(el("dd", null, FIELD_HELP[k]));
      }
      return dl;
    })(),

    el("h3", null, "How the feed is built"),
    el("ul", { class: "bullets" }, [
      el("li", null, "The CVE universe is the distro OVAL feed intersected with the packages actually installed in the newest scanned VHD build."),
      el("li", null, "For each affected package the tool scans a set of recent VHD build release notes (anchored at a fixed floor version, e.g. the start of the year) plus the latest security-patch deltas, and records the earliest build that reaches the fixed version."),
      el("li", null, "Azure Linux uses Microsoft's OVAL plus the MSRC CSAF/VEX feed (for not_affected / under_investigation / affected verdicts); Ubuntu uses Canonical's per-release CVE OVAL plus the Ubuntu CVE Tracker (for not_affected / under_investigation / affected / will_not_fix verdicts)."),
    ]),

    el("h3", null, "Known limitations"),
    el("ul", { class: "bullets" }, [
      el("li", null, [el("strong", null, "Additive surface not assessed. "),
        FIELD_HELP.additive]),
      el("li", null, [el("strong", null, "'Affected' is rarely emitted. "),
        "A CVE with no upstream fix can't be enumerated from OVAL alone, so 'affected' is only surfaced where the vendor VEX / Ubuntu CVE Tracker asserts it; otherwise the feed focuses on fixed / fix_available_upstream verdicts."]),
      el("li", null, [el("strong", null, "Windowed. "),
        "Only CVEs whose fix status is determined within the scanned build window appear; issues fixed before the window are treated as old news."]),
    ]),

    el("h3", null, "Ordering"),
    el("p", { class: "note" }, "Advisories are listed newest CVE first \u2014 sorted by CVE year then sequence number (descending). There is no per-CVE publication date in the feed, so the CVE id is used as a recency proxy. The Updated column shows when the record was last regenerated by the daily feed build, which is the same date for every row in a given run."),

    el("h3", null, "Using search & filters"),
    el("ul", { class: "bullets" }, [
      el("li", null, "Search matches a CVE id substring (e.g. \"2026-4\")."),
      el("li", null, "OS / SKU filters by VHD lineage label; Status and Severity narrow further. Combine them freely, then Reset to clear."),
    ]),

    el("p", { class: "note" }, [
      "Full schema and build documentation live in the ",
      el("a", { href: "https://github.com/chrischangcode/aks-security-advisory/tree/main/docs", target: "_blank", rel: "noopener" },
        "project docs"),
      ".",
    ]),
  ]);
  $app().replaceChildren(view);
  window.scrollTo(0, 0);
}

/* ---------- footer / routing ---------- */

function setGeneratedFooter() {
  const g = document.getElementById("feed-generated");
  if (g && state.index && state.index.generated) {
    g.textContent = "Feed generated " + state.index.generated +
      " \u00b7 " + state.index.count + " advisories.";
  }
}

async function route() {
  const hash = location.hash.replace(/^#\/?/, "");
  if (!state.index) return;  // initial load handles first render
  if (/^help$/i.test(hash)) {
    renderHelp();
  } else if (hash && /^CVE-/i.test(hash)) {
    $app().replaceChildren(el("p", { class: "loading" }, "Loading " + hash + "\u2026"));
    try {
      renderDetail(await loadAdvisory(hash.toUpperCase()));
    } catch (e) {
      $app().replaceChildren(el("div", { class: "error" },
        "Could not load advisory " + hash + " (" + e.message + ")."));
    }
    window.scrollTo(0, 0);
  } else {
    renderList();
  }
}

async function main() {
  try {
    await loadIndex();
  } catch (e) {
    $app().replaceChildren(el("div", { class: "error" },
      "Failed to load the advisory feed (" + e.message + "). " +
      "If running locally, serve the repo root and open /site/, or pass ?data=<path>."));
    return;
  }
  setGeneratedFooter();
  window.addEventListener("hashchange", route);
  await route();
}

document.addEventListener("DOMContentLoaded", main);
